[workspace]
resolver = "2"
members = ["backend/hello"]

[dependencies]
ed25519-dalek = "1.1.3"
chacha20poly1305 = "0.10.0"
rand = "0.8.7"
serde = { version = "1.0.193", features = ["derive"] }
serde_cbor = "0.12.1"
